import { Poetsen_One, Raleway, Poppins, Roboto } from 'next/font/google';
import './globals.css';

// Define your fonts with subsets for optimal loading
const poetsenOne = Poetsen_One({
  subsets: ['latin'],
  weight: '400', // Poetsen One typically has only one weight
  variable: '--font-poetsen-one', // Custom CSS variable for Tailwind
  display: 'swap',
});

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway', // Custom CSS variable for Tailwind
  display: 'swap',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Adjust weights as needed
  variable: '--font-poppins', // Custom CSS variable for Tailwind
  display: 'swap',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Adjust weights as needed
  variable: '--font-roboto', // Custom CSS variable for Tailwind
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poetsenOne.variable} ${raleway.variable} ${poppins.variable} ${roboto.variable}`}
    >
      <body className="bg-brand-background-light-300 dark:bg-brand-background-dark-950 antialiased">
        {children}
      </body>
    </html>
  );
}
